# Generated by Django 4.2.7 on 2026-09-14 10:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=12)),
                ('level', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL, verbose_name='Referred User')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Sponsor')),
            ],
            options={
                'verbose_name': 'Referral Relationship',
                'verbose_name_plural': 'Referral Relationships',
            },
        ),
        migrations.CreateModel(
            name='ReferralPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard 2-Level Demo Plan', max_length=100)),
                ('level_1_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Direct sponsor reward percentage (e.g. 0.0500 = 5.00%).', max_digits=6, verbose_name='Level 1 Rate')),
                ('level_2_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Second-level sponsor reward percentage (e.g. 0.0200 = 2.00%).', max_digits=6, verbose_name='Level 2 Rate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referral Plan',
                'verbose_name_plural': 'Referral Plans',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Referral Level (1 or 2)')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='PROCESSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_received', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiary User')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_reward_entries', to='wallet.wallettransaction')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='referrals.referral')),
                ('source_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='rewards.rewardposition')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_generated', to=settings.AUTH_USER_MODEL, verbose_name='Source User')),
            ],
            options={
                'verbose_name': 'Demo Referral Reward',
                'verbose_name_plural': 'Demo Referral Rewards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['beneficiary_user', 'created_at'], name='idx_ref_reward_user')],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer'], name='idx_ref_referrer'),
        ),
    ]
