# Generated by Django 4.2.7 on 2026-09-14 05:49

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Required. Primary email used for login and notifications.', max_length=255, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(help_text="Required. User's full legal name.", max_length=150, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth.", null=True, verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(db_index=True, help_text='Required. Unique mobile number (e.g. Bangladesh format).', max_length=20, unique=True, verbose_name='Mobile Number')),
                ('highest_education', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('DIPLOMA', 'Diploma'), ('BACHELOR', "Bachelor's"), ('MASTER', "Master's"), ('MPHIL', 'MPhil'), ('PHD', 'PhD'), ('OTHER', 'Other')], default='BACHELOR', help_text='Highest completed education qualification.', max_length=20, verbose_name='Highest Education Level')),
                ('institution_name', models.CharField(blank=True, help_text='College, University, or Institute name.', max_length=255, verbose_name='Institution Name')),
                ('subject', models.CharField(blank=True, help_text='Field of study or major subject.', max_length=150, verbose_name='Subject / Major')),
                ('passing_year', models.PositiveIntegerField(blank=True, help_text='Year of completion / graduation.', null=True, verbose_name='Passing Year')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='Email Verified')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.', verbose_name='Active Status')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Cryptographically hashed verification code (never stored as plain text).', max_length=128, verbose_name='Hashed Verification Code')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Time after which this verification code is no longer valid.', verbose_name='Expiration Time')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Counter for invalid attempts to prevent brute-force attacks.', verbose_name='Verification Attempts')),
                ('is_used', models.BooleanField(default=False, help_text='Marks whether this verification code has already been redeemed.', verbose_name='Is Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Verification Code',
                'verbose_name_plural': 'Email Verification Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='idx_verif_user_used'), models.Index(fields=['expires_at'], name='idx_verif_expires')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mobile_number'], name='idx_user_mobile'),
        ),
    ]
