# Generated by Django 4.2.7 on 2026-09-14 10:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Demo 2% / 75-Day Simulation', max_length=100, verbose_name='Plan Name')),
                ('daily_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Decimal rate (e.g. 0.0200 = 2.00% per day).', max_digits=6, verbose_name='Daily Rate')),
                ('duration_days', models.PositiveIntegerField(default=75, help_text='Total simulation days before position completes.', verbose_name='Duration (Days)')),
                ('minimum_demo_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=18, verbose_name='Minimum Demo Amount')),
                ('maximum_demo_amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=18, verbose_name='Maximum Demo Amount')),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=True, help_text='Ensures this plan only executes in simulated demo mode.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward Plan',
                'verbose_name_plural': 'Reward Plans',
            },
        ),
        migrations.CreateModel(
            name='RewardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_amount', models.DecimalField(decimal_places=2, help_text='Initial virtual funds debited from user wallet.', max_digits=18, verbose_name='Allocated Demo Amount')),
                ('daily_rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Applied Daily Rate')),
                ('duration_days', models.PositiveIntegerField(default=75, verbose_name='Duration (Days)')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End Date')),
                ('total_reward_limit', models.DecimalField(decimal_places=2, help_text='Maximum lifetime rewards this position can produce (e.g. 150 DUSD for 100 DUSD at 2% x 75 days).', max_digits=18, verbose_name='Total Reward Limit')),
                ('reward_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Reward Earned')),
                ('last_reward_date', models.DateField(blank=True, null=True, verbose_name='Last Reward Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reward_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='rewards.rewardplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_positions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Demo Reward Position',
                'verbose_name_plural': 'Demo Reward Positions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateField(db_index=True, verbose_name='Reward Date')),
                ('calculation_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Base Amount')),
                ('reward_rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Reward Rate')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Reward Credited')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('SKIPPED', 'Skipped'), ('REVERSED', 'Reversed')], default='PROCESSED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reward_entries', to='wallet.wallettransaction')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rewards', to='rewards.rewardposition', verbose_name='Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rewards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Daily Demo Reward',
                'verbose_name_plural': 'Daily Demo Rewards',
                'ordering': ['-reward_date'],
            },
        ),
        migrations.AddIndex(
            model_name='rewardposition',
            index=models.Index(fields=['user', 'status'], name='idx_pos_user_status'),
        ),
        migrations.AddIndex(
            model_name='rewardposition',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='idx_pos_active_dates'),
        ),
        migrations.AddIndex(
            model_name='dailyreward',
            index=models.Index(fields=['position', 'reward_date'], name='idx_daily_pos_date'),
        ),
        migrations.AddIndex(
            model_name='dailyreward',
            index=models.Index(fields=['user', 'reward_date'], name='idx_daily_user_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyreward',
            constraint=models.UniqueConstraint(fields=('position', 'reward_date'), name='unique_position_reward_date'),
        ),
    ]
