# Generated by Django 4.2.7 on 2026-09-14 10:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Requested Demo Amount')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Simulated Fee')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Net Demo Amount')),
                ('method', models.CharField(choices=[('DEMO_BANK', 'Demo Bank Transfer (Simulation)'), ('DEMO_MOBILE_WALLET', 'Demo Mobile Wallet (Simulation)'), ('DEMO_CRYPTO', 'Demo Crypto Address (Simulation)')], default='DEMO_MOBILE_WALLET', max_length=32, verbose_name='Simulated Payout Method')),
                ('account_name', models.CharField(max_length=150, verbose_name='Account Holder Name')),
                ('account_identifier', models.CharField(help_text='e.g. TEST-01712345678 or 0xDEMO...', max_length=150, verbose_name='Account / Wallet Identifier')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing Simulation'), ('COMPLETED', 'Completed (Simulation)'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Note')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Demo Withdrawal',
                'verbose_name_plural': 'Demo Withdrawals',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_withdr_user_status'), models.Index(fields=['status', 'requested_at'], name='idx_withdr_status_req')],
            },
        ),
    ]
