# Generated by Django 4.2.7 on 2026-09-14 10:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='DUSD', help_text='Virtual demo currency identifier (e.g. DUSD).', max_length=10, verbose_name='Currency Code')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Simulated balance available for demo allocations or withdrawals.', max_digits=18, verbose_name='Available Demo Balance')),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Simulated balance held pending withdrawal approval or active lock.', max_digits=18, verbose_name='Locked Demo Balance')),
                ('lifetime_credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Lifetime Demo Credited')),
                ('lifetime_debited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Lifetime Demo Debited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Demo Wallet',
                'verbose_name_plural': 'Demo Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEMO_DEPOSIT', 'Demo Deposit'), ('DEMO_POSITION_ALLOCATION', 'Demo Position Allocation'), ('DEMO_REWARD', 'Daily Demo Reward'), ('REFERRAL_REWARD', 'Demo Referral Reward'), ('DEMO_WITHDRAWAL', 'Demo Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal Reversal'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin Demo Adjustment'), ('REVERSAL', 'Reversal')], db_index=True, max_length=32, verbose_name='Transaction Type')),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10, verbose_name='Direction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Available Balance Before')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Available Balance After')),
                ('reference_type', models.CharField(blank=True, help_text='Entity type e.g. RewardPosition, DailyReward, Withdrawal.', max_length=64, verbose_name='Reference Type')),
                ('reference_id', models.CharField(blank=True, help_text='Primary key of referenced object.', max_length=64, verbose_name='Reference ID')),
                ('description', models.CharField(help_text='Clear explanation, always prefixed with [DEMO].', max_length=255, verbose_name='Description')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Guaranteed unique identifier preventing duplicate transaction processing.', max_length=128, unique=True, verbose_name='Idempotency Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='idx_tx_wallet_created'), models.Index(fields=['transaction_type'], name='idx_tx_type'), models.Index(fields=['idempotency_key'], name='idx_tx_idempotency')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='idx_wallet_user'),
        ),
    ]
