# Generated by Django 4.2.7 on 2026-09-14 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('EMAIL_VERIFIED', 'Email Verified'), ('LOGIN_SUCCESS', 'Login Succeeded'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_RESET', 'Password Reset'), ('DEMO_DEPOSIT', 'Demo Deposit Credited'), ('POSITION_CREATED', 'Reward Position Allocated'), ('REWARD_CREDITED', 'Daily Demo Reward Credited'), ('REFERRAL_REWARD', 'Referral Reward Credited'), ('WITHDRAWAL_CREATED', 'Withdrawal Requested'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('ADMIN_ADJUSTMENT', 'Admin Demo Adjustment'), ('POSITION_PAUSED', 'Position Paused'), ('POSITION_RESUMED', 'Position Resumed'), ('POSITION_CANCELLED', 'Position Cancelled')], db_index=True, max_length=64, verbose_name='Action Type')),
                ('entity_type', models.CharField(blank=True, help_text='e.g. Wallet, RewardPosition, Withdrawal.', max_length=64, verbose_name='Entity Type')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='Entity ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_admin_audits', to=settings.AUTH_USER_MODEL, verbose_name='Admin Actor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Subject User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='idx_audit_action_date'), models.Index(fields=['user', 'action'], name='idx_audit_user_action')],
            },
        ),
    ]
